#!/bin/sh
#
# @name ASL Actuator Test
#
# @type Actuator Test
# @class Experiment
#
# @output MAIN1 servo
# @output MAIN2 servo
# @output MAIN3 motor
# @output MAIN4 servo
# @output MAIN5 servo
# @output MAIN6 servo
#

set VEHICLE_TYPE actuator_test

param set PWM_MIN 1000
param set PWM_MAX 2000
param set PWM_RATE 50
param set PWM_DISARMED 1500

set MIXER asl_actuator_test

set PWM_OUT 12345678
set PWM_RATE p:PWM_RATE
set PWM_DISARMED p:PWM_DISARMED
set PWM_MIN p:PWM_MIN
set PWM_MAX p:PWM_MAX
